import datetime

request_text = f"""TO: police.records@cantonohio.gov
CC: tami.ketler@cantonohio.gov
SUBJECT: PUBLIC RECORDS REQUEST - R.C. 149.43 - 1718 North Market Place NW Incident

PUBLIC RECORDS REQUEST
(Pursuant to Ohio Revised Code § 149.43)

DATE: {datetime.date.today().strftime("%B %d, %Y")}

TO:
Canton Police Department / Records Bureau
City of Canton Records Custodian
221 3rd Street SW, Canton, OH 44702
Email: police.records@cantonohio.gov

CC:
City of Canton Law Department
Records Custodian: Tami Ketler
Email: tami.ketler@cantonohio.gov

FROM:
Dwayne Jones
120 E. 44th Street, Apt 2E, Chicago, IL 60653
Phone: (773) 440-3343
Email: DwayneJones696@gmail.com

RE: PUBLIC RECORDS REQUEST – SEPTEMBER 17 CALL SERVICE LOGS, BODY-WORN CAMERA FOOTAGE, AND POLICE REPORTS

Dear Records Custodian:

Per my telephone inquiry, I am currently residing out of state in Chicago, Illinois. Pursuant to Ohio Revised Code § 149.43(B)(7), I am exercising my legal right to request these records electronically via email. 

Pursuant to the Ohio Public Records Act (R.C. § 149.43), I hereby respectfully request copies of all public records generated by, received by, or in the possession of the Canton Police Department regarding an incident/dispatch call that occurred on September 17 involving Child Protective Services (CPS) / Stark County Job & Family Services caseworker Carly Sanders and the removal or welfare check of minor child Demari Jones at the address 1718 North Market Place Northwest Avenue, Canton, Ohio.

SPECIFIC RECORDS REQUESTED:
1. Call Service Logs & Dispatch Records: Computer-Aided Dispatch (CAD) incident reports, run sheets, call logs, dispatch audio recordings, and 911 calls associated with 1718 North Market Place Northwest Avenue for September 17.
2. Police Reports: Complete incident reports, officer narrative reports, supplemental reports, field notes, and arrest/citation records.
3. Audio & Video Recordings: All Body-Worn Camera (BWC) footage and dash camera/cruiser video from all responding officers and personnel present at or dispatched to the scene.
4. Personnel & On-Scene Log: A list of all police officers, deputies, supervisors, and administrative personnel assigned to or present at the scene.
5. Inter-Agency Communications: Any written communications, emails, intake notes, or agency request forms exchanged between the Canton Police Department and CPS/Stark County Job and Family Services (including caseworker Carly Sanders) regarding this incident.

PLEASE TRANSMIT RECORDS ELECTRONICALLY TO: DwayneJones696@gmail.com.

Respectfully submitted,

/s/ Dwayne Jones
Dwayne Jones
120 E. 44th Street, Apt 2E, Chicago, IL 60653
Phone: (773) 440-3343
Email: DwayneJones696@gmail.com
"""

with open("PUBLIC_RECORDS_REQUEST.txt", "w") as f:
    f.write(request_text)

    print("[+] PUBLIC_RECORDS_REQUEST.txt generated successfully.")